# Generated by Django 5.1.3 on 2026-05-19 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_photo_reservation_statut_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifs',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='home.service'),
        ),
    ]
