# Generated by Django 5.1.3 on 2026-05-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tarifs_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='experts/'),
        ),
    ]
