# Generated by Django 5.1.3 on 2026-05-20 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_expert_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFormation', models.CharField(max_length=100)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree', models.DurationField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.expert')),
            ],
        ),
    ]
