# Generated by Django 5.1.3 on 2026-05-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_expert_public_profile_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('attente', 'en attente'), ('confirme', 'confirme'), ('decline', 'decline')], default='attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarifs',
            name='typeTarif',
            field=models.CharField(choices=[('heure', 'A l heure'), ('forfait', 'Forfaitaire')], max_length=20),
        ),
    ]
