# Generated by Django 5.1.3 on 2026-06-01 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactmessage_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='realisations/')),
                ('lien', models.URLField(blank=True, null=True)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('est_publiee', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations', to='home.expert')),
                ('services', models.ManyToManyField(blank=True, related_name='realisations', to='home.service')),
            ],
        ),
    ]
