# Generated by Django 5.1.3 on 2026-06-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_realisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
