# Generated by Django 5.1.3 on 2026-08-24 03:19

import django.core.validators
import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_portfolio_portfoliophoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-date_shooting', '-created_at', 'titre']},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_shooting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='est_publie',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='portfoliophoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolioPhotos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), home.models.validate_portfolio_image_size]),
        ),
    ]
